import { Nunito_Sans, DM_Sans, Lora } from "next/font/google";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito-sans",
  display: "swap",
});
const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  display: "swap",
});
const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  display: "swap",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${nunitoSans.className} ${dmSans.className} ${lora.className} antialiased`}
        className={`${nunitoSans.variable} ${dmSans.variable} ${lora.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
